### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by TxHawks** [pattern-lab/edition-php-development#13]
I just tried to install the dev version and I get the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pattern-lab/starterkit-mustache-demo dev-dev -> satisfiable by pattern-lab/starterkit-mustache-demo[dev-dev].
    - pattern-lab/starterkit-mustache-demo dev-dev requires pattern-lab/core ~0.5 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by dmolsen** [comment]
@TxHawks -

Good catch. I've updated the dependencies on `dev`. Looks like a bad merge.

**Comment by TxHawks** [comment]
Still no go. I now get:

```
PHP Fatal error:  Call to undefined method Composer\Script\Event::getOperation() in /var/www/pl-demo/vendor/pattern-lab/core/src/PatternLab/InstallerUtil.php on line 559

Fatal error: Call to undefined method Composer\Script\Event::getOperation() in /var/www/pl-demo/vendor/pattern-lab/core/src/PatternLab/InstallerUtil.php on line 559
```

**Comment by dennisfrank** [comment]
Me and a colleague are getting the same fatal errors in InstallerUtil.php on line 559.

**Comment by dmolsen** [comment]
Most likely this is an issue w/ Composer. Can you both share which version of Composer you're using? You can run `composer -v` to get that info. 

There was an update that broke how certain events are handled but before I have you update I may want to try to make my code more backwards compatible. Thanks.

**Comment by dennisfrank** [comment]
Composer version 1.0-dev (bc45d9185513575434021527d7756420e9f4b2cf) 2015-05-11 14:49:39

**Comment by dmolsen** [comment]
@dennisfrank -

Ugh. Ok, yours is newer than mine so... Fun ;)

**Comment by dennisfrank** [comment]
@dmolsen That’s what I got with `curl -sS https://getcomposer.org/installer | php` 

¯\_(ツ)_/¯

**Comment by TxHawks** [comment]
1.0-dev here as well

**Comment by darren131** [comment]
Don't mean to just tack on to this thread in such a negative fashion... but I, too, am having that error running composer 1.0-dev.

**Comment by TxHawks** [comment]
@dmolsen -

I now get a different error message on both this edition and the Twig edition:

```
Script PatternLab\Installer::postPackageInstall handling the post-package-install event terminated with an exception

[UnexpectedValueException]
RecursiveDirectoryIterator::__construct(/home/txh/delme/new/pattern-lab/packages/pattern-lab/styleguidekit-assets-default/dist/fonts): failed to open dir: No such file or directory
```

Also, for the time being, Is there a way to install PL manually, sans composer?

**Comment by tamieilat** [comment]
@dmolsen -

Any update on this? 

I've now tested this on Linux (Ubuntu), Mac and Windows machines, and get the same error. 

Thanks

**Comment by TxHawks** [comment]
Quick and dirty fix for this issue:
run 
`composer create-project pattern-lab/edition-development your-project-name && cd $_` or
`composer create-project pattern-lab/edition-development-twig your-project-name && cd $_` or
`composer create-project pattern-lab/edition-twig-standard your-project-name && cd $_`
as usual, which will fail as above.

Then, run `composer install` (From within your project dir). When prompted on whether to to merge or replace `./public/styleguide/bower_components`, open another terminal window, and in your project directory, type `mkdir packages/pattern-lab/styleguidekit-assets-default/dist/images packages/pattern-lab/styleguidekit-assets-default/dist/fonts`.

After creating the directories, go back to the first terminal and complete the installation process.

Pattern Lab should now work

**Comment by dmolsen** [comment]
Not that this help anyone much but the Mustache edition is now installing cleanly for me. I made some tweaks to handle Mustache 2.9.0 as well as the latest edition of Composer. Feel free to chime in with further issues. Schedule has finally died down.

**Comment by TxHawks** [comment]
@dmolsen - 
Thanks. Installation of dev editions are now okay again, but only on Linux and Mac. Windows installations still fail, so edition-php-twig-development#19 is still an issue.

Progress on edition-php-twig-development#15 would also be very helpful.
