### ISSUE TITLE
Patter loader error when generating patterns

### ISSUE THREAD

**Issue by iansoper** [pattern-lab/edition-php-development#15]
When I try to generate a pattern, I get this error:

```bash
$ php core/console --generate
configuring pattern lab...
the supplied pattern extension didn't match a pattern loader rule. check your config...
```

I'm using edition-php-development out of the box, no patterns added, no config changes. It is using mustache patterns by default. I did use install fixes from #13.

**Comment by dmolsen** [comment]
@iansoper -

This was a bad config in the Mustache pattern engine. Fixed way too late for your needs. Sorry. Documenting in case someone else asks.
