### ISSUE TITLE
Pseudo-pattern array inheritance issue

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/edition-php-development#18]
I have an array defined in `list.json` that looks like this:

```````````
"lis" : [
	{ "liText" : "Text" },
	{ "liText" : "More Text" },
	{ "liText" : "Even More Text" }
]
`````````
This renders as a bulleted list on the front end. 

I then have a pseudo-pattern called `list~new.json` that wipes out the existing list with a single list item with no text. That looks like this:

```````````
"lis" : [
	{ "liText" : "" }
]
```````````

The issue is that the list now renders on the frontend as such:

- 
- More Text
- Even More Text

In short, the original array isn't wiped out completely, only the first item. If I recall correctly, this was an issue with PL 1.0 that got resolved somewhere along the line.

**Comment by dmolsen** [comment]
While it seems weird I'm going to match the function used in the PL 1.0 pseudo-pattern set-up. That way it'll work the way you expected and how it probably should. I'll throw that in this afternoon.

**Comment by dmolsen** [comment]
Try this now. Should work the way you expect. Not sure if it'll have knock-on effects though. Hasn't in my tests at least. Again, it's `composer update pattern-lab/core`.

**Comment by bradfrost** [comment]
I checked this out, and yep! It's working correctly now.
