### ISSUE TITLE
Pulled Down Working Version of Pattern Lab Version 2, But It Is Not Working

### ISSUE THREAD

**Issue by frostyweather** [pattern-lab/edition-php-development#19]
Brad just updated pattern lab for the site we have been working on. However, when he pushed it in Git Tower and I pulled down, the site did not generate.

Tried running <pre><code>php core/console --generate</code></pre>
But got an error:
<pre><code>Fatal error: Class 'PatternLab\Timer' not found in /Users/ian/Sites/listy/pl/core/console on line 35</code></pre>

Also tried updating composer:
<pre><code>composer update pattern-lab/core</code></pre>
But got more errors:
<pre><code>Fatal error: Class '\PatternLab\Composer\UnifiedAssetInstaller' not found in phar:///usr/local/bin/composer/src/Composer/Plugin/PluginManager.php on line 154</code></pre>

Also tried:
<pre><code>composer update</code></pre> and <pre><code>composer update self-update</code></pre> and got the same error as above.

Do you have any ideas on how to remedy this? Thanks!

**Comment by dmolsen** [comment]
Commented on this on the project repo you have.
