### ISSUE TITLE
Bootstrap and Foundation Starterkits Bleed To Edge of Page/List Styles Show Up

### ISSUE THREAD

**Issue by frostyweather** [pattern-lab/edition-php-development#20]
Bootstrap and foundation starterkits bleed to edge of page when you remove the ```style.css``` file from the head. This should be built in concretely into ```styleguide.css``` so even when you remove ```style.css``` from the head, the contents don't bleed to the edge of the page. Is there a bug with ```styleguide.css```?

Here is the bleeding and color list-styles happening in both Foundation and Bootstrap:
![screen shot 2015-12-10 at 4 48 00 pm](https://cloud.githubusercontent.com/assets/13662843/11729727/c62f4792-9f5e-11e5-8e63-7e4922823b39.png)
![screen shot 2015-12-10 at 4 48 16 pm](https://cloud.githubusercontent.com/assets/13662843/11729728/c632d2d6-9f5e-11e5-9253-f851b5c697e0.png)

**Comment by bradfrost** [comment]
This has been addressed and is now in dev: https://github.com/pattern-lab/styleguidekit-assets-default/tree/dev
