### ISSUE TITLE
Remove MQs from menu

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/edition-php-development#5]
While this is a useful feature, it isn't a core PL feature and should be implemented as a plugin. @dmolsen , is it alright if I remove this from the menu?

**Comment by dmolsen** [comment]
Have at it :)

**Comment by bradfrost** [comment]
![christmas-vacation-clark-chainsaw-jason-mask-photo](https://cloud.githubusercontent.com/assets/383701/6908898/cc92e404-d6f5-11e4-9564-9b16c5487d9f.jpg)

**Comment by bradfrost** [comment]
Media queries have been removed from the menu
